CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    password_hash text NOT NULL,
    is_staff boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    response_minutes integer NOT NULL CHECK (response_minutes > 0)
);
CREATE TABLE IF NOT EXISTS tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    category_id integer NOT NULL REFERENCES categories(id),
    title text NOT NULL,
    body text NOT NULL,
    status text NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'in_progress', 'closed')),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES tickets(id),
    user_id integer NOT NULL REFERENCES users(id),
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
